# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: About
    path: about
    class: _navabout
  - label: Projects
    path: projects/
    class: _navprojects
  - label: Sketches
    path: sketches/
    class: _navsketches
  - label: Blog
    link: http://librarylab.law.harvard.edu/blog
    class: _navblog
  - label: We're Hiring!
    path: jobs
    class: _navjobs
