# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus

main:
  - label: About
    title: About
    path: about
    class: first
  - label: Projects
    path: projects/
  - label: Sketches
    path: sketches/
  - label: Blog
    link: http://librarylab.law.harvard.edu/blog
  - label: Contact
    link: contact
    class: last
